import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  containerMain: {
    backgroundColor: '#F2F2F2',
    height: 'auto',
    paddingTop: 50,
    paddingBottom: 50,
  },
  btnRegis: {
    marginBottom: 50,
    backgroundColor: '#6A4029',
    borderRadius: 20,
    height: 70,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    marginBottom: 100,
    marginHorizontal: '10%',
  },
  textBtnRegis: {
    color: 'white',
    fontWeight: 'bold',
    fontFamily: 'Poppins-Regular',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 17,
    lineHeight: 26,
  },
  textTitle: {
    color: 'black',
    fontFamily: 'Poppins-Bold',
    fontStyle: 'normal',
    fontWeight: '900',
    fontSize: 34,
    lineHeight: 51,
    marginHorizontal: '10%',
    marginBottom: 30,
  },
  textHead: {
    color: 'black',
    fontFamily: 'Poppins-Regular',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 18,
    lineHeight: 27,
    marginHorizontal: '10%',
  },
  textTriger: {
    color: '#6A4029',
    fontFamily: 'Poppins-Regular',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 15,
    lineHeight: 22,
    marginHorizontal: '10%',
  },
  textBold: {
    color: 'black',
    fontFamily: 'Poppins-Regular',
    fontStyle: 'normal',
    fontWeight: '900',
    fontSize: 18,
    lineHeight: 27,
  },
  boxProfile: {
    height: 'auto',
    flex: 1,
    marginTop: 9,
    marginHorizontal: '10%',
    paddingVertical: 26,
    paddingHorizontal: 5,
    borderRadius: 20,
    flexDirection: 'row',
    backgroundColor: 'white',
    marginBottom: 24,
  },
  boxImgInfo: {
    height: '100%',
    flex: 1,
    alignItems: 'center',
    backgroundColor: 'yellow',
  },
  imgProfile: {
    height: 70,
    width: 70,
    borderRadius: 200,
    marginLeft: '10%',
  },
  boxTextInfo: {
    width: 100,
    height: 150,
    flex: 1,
    paddingRight: 10,
  },
  textInfo: {
    color: 'rgba(106, 64, 41, 0.6)',
    fontFamily: 'Poppins-Regular',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 15,
    lineHeight: 22,
    paddingVertical: 8,
    borderBottomWidth: 0.5,
    borderBottomColor: 'rgba(0, 0, 0, 0.5)',
  },
  textAddress: {
    color: 'rgba(106, 64, 41, 0.6)',
    fontFamily: 'Poppins-Regular',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 15,
    lineHeight: 22,
    paddingVertical: 8,
  },
  boxMenu: {
    backgroundColor: 'white',
    marginHorizontal: '10%',
    marginBottom: 27,
    height: 60,
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 20,
  },
});
