import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  containerMain: {
    backgroundColor: '#F2F2F2',
    height: 'auto',
    paddingTop: 50,
    paddingBottom: 50,
    paddingHorizontal: '10%',
  },
  btnRegis: {
    marginTop: 20,
    marginBottom: 30,
    backgroundColor: '#6A4029',
    borderRadius: 20,
    height: 70,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    marginBottom: 100,
  },
  textBtnRegis: {
    color: 'white',
    fontWeight: 'bold',
    fontFamily: 'Poppins-Regular',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 17,
    lineHeight: 26,
  },
  boxHeader: {
    alignItems: 'center',
    paddingBottom: 20,
    marginBottom: 30,
  },
  imgUser: {
    width: 130,
    height: 130,
    borderRadius: 200,
  },
  iconEdit: {
    marginTop: -40,
    marginLeft: 95,
    backgroundColor: '#6A4029',
    width: 30,
    height: 30,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkInput: {
    flexDirection: 'row',
    marginBottom: 21,
  },
  textForm: {
    color: 'black',
    fontFamily: 'Poppins-Reguler',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 13,
    lineHeight: 20,
    marginLeft: 20,
  },
  boxForm: {
    marginBottom: 21,
  },
  textTitle: {
    color: '#9F9F9F',
    fontFamily: 'Poppins-Bold',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 13,
    lineHeight: 20,
  },
  inputForm: {
    borderBottomWidth: 1,
    borderBottomColor: '#9F9F9F',
    height: 42,
    color: 'black',
    fontFamily: 'Poppins-Reguler',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 13,
    lineHeight: 20,
  },
  inputFormDate: {
    paddingVertical: 10,
    flex: 1,
    height: 42,
    color: 'black',
    fontFamily: 'Poppins-Reguler',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 13,
    lineHeight: 20,
  },
  inputPlaceDate: {
    paddingVertical: 10,
    flex: 1,
    height: 42,
    color: '#9F9F9F',
    fontFamily: 'Poppins-Reguler',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 13,
    lineHeight: 20,
  },
  // date form
  inputDate: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 1,
    fontFamily: 'Poppins-Regular',
    fontWeight: '700',
    fontSize: 14,
    borderBottomColor: '#9F9F9F',
    color: 'white',
    lineHeight: 21,
  },
  //   pass form
  inputPass: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    fontFamily: 'Poppins-Regular',
    fontWeight: '700',
    fontSize: 14,
    borderBottomColor: '#9F9F9F',
    color: 'white',
    lineHeight: 21,
  },
  inputFormPass: {
    flex: 9,
    color: 'black',
    fontFamily: 'Poppins-Reguler',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 13,
    lineHeight: 20,
  },
  iconPass: {
    width: 25,
    height: 25,
  },
  textHead: {
    color: 'black',
    fontFamily: 'Poppins-Regular',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 18,
    lineHeight: 27,
    marginBottom: 20,
  },
});
