import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  containerMain: {
    backgroundColor: '#F2F2F2',
    height: 'auto',
    marginBottom: 10,
    paddingTop: 30,
    paddingBottom: 100,
    paddingHorizontal: '10%',
  },
  boxMain: {
    backgroundColor: 'white',
    minHeight: 300,
    padding: 5,
    paddingHorizontal: 10,
    borderRadius: 12,
  },
  boxDaily: {
    marginBottom: 30,
    backgroundColor: 'white',
    minHeight: 300,
    padding: 5,
    paddingHorizontal: 10,
    marginTop: 30,
    borderRadius: 12,
  },
  boxHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  textHead: {
    fontFamily: 'Poppins-Bold',
    color: 'black',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 22,
    lineHeight: 33,
  },
  textTitle: {
    fontFamily: 'Poppins-Bold',
    color: 'black',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 28,
    lineHeight: 42,
  },
  textInfo: {
    fontFamily: 'Poppins-Reguler',
    color: '#7C828A',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 24,
  },
  //   chart
  infoChart: {
    height: '100%',
    flex: 1,
  },
  mainChart: {
    height: '100%',
    flex: 4,
  },
  //   box Info
  infoHead: {
    width: '100%',
    flex: 6,
    paddingEnd: 3,
    justifyContent: 'space-between',
  },
  textRange: {
    fontFamily: 'Poppins-Reguler',
    color: '#7C828A',
    textAlign: 'right',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 18,
  },
  infoFoot: {
    width: '100%',
    flex: 1,
  },
  //   box chart
  boxChart: {
    width: '100%',
    flex: 5,
    borderColor: '#7C828A',
    borderBottomWidth: 1,
    borderStyle: 'dashed',
    flexDirection: 'row',
  },
  boxChartDaily: {
    width: '100%',
    flex: 5,
    flexDirection: 'row',
  },
  boxBullet: {
    flex: 1,
    height: '98%',
    marginBottom: '2%',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  listChart: {
    width: '100%',
    flex: 1,
    flexDirection: 'row',
  },
  boxList: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textList: {
    fontFamily: 'Poppins-Reguler',
    color: '#7C828A',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 18,
    textTransform: 'uppercase',
  },
  textListDaily: {
    fontFamily: 'Poppins-Bold',
    color: 'black',
    fontStyle: 'normal',
    fontWeight: '800',
    fontSize: 12,
    lineHeight: 18,
    textTransform: 'uppercase',
  },
  //   foot main cart
  infoLegend: {
    height: 50,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  textFoot: {
    marginLeft: 10,
    fontFamily: 'Poppins-Reguler',
    color: '#7C828A',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 10,
    lineHeight: 15,
  },
  lastBox: {
    backgroundColor: 'white',
    height: 350,
    padding: 5,
    paddingHorizontal: 10,
    borderRadius: 12,
    marginBottom: 50,
    alignItems: 'center',
  },
  textUp: {
    fontFamily: 'Nunito-Sans',
    color: 'black',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 22,
    lineHeight: 30,
    marginTop: 22,
    marginBottom: 8,
  },
  textDesc: {
    fontFamily: 'Nunito-Sans',
    color: '#7C828A',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 22,
    textAlign: 'center',
  },
  imgView: {
    backgroundColor: 'rgba(115, 136, 169, 0.353283)',
    width: 160,
    height: 160,
    borderRadius: 300,
    marginTop: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  boxText: {
    backgroundColor: 'white',
    width: 120,
    height: 120,
    borderRadius: 300,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textLast: {
    fontFamily: 'Nunito-Sans',
    color: 'black',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 22,
    lineHeight: 30,
    textAlign: 'center',
  },
});
