import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  containerMain: {
    height: '100%',
    justifyContent: 'space-between',
  },
  textHeader: {
    fontSize: 65,
    color: 'white',
    marginTop: 78,
    marginLeft: '5%',
    fontWeight: '700',
  },
  sectionForm: {
    padding: '5%',
  },
  textForm: {
    marginHorizontal: '5%',
    paddingHorizontal: 10,
    color: 'white',
    marginVertical: 10,
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 12,
    lineHeight: 18,
  },
  //   pass form
  inputPass: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    paddingHorizontal: 5,
    fontFamily: 'poppins',
    fontWeight: '700',
    fontSize: 14,
    borderColor: 'white',
    color: 'white',
    lineHeight: 21,
  },
  inputFormPass: {
    flex: 9,
    color: 'white',
    fontFamily: 'poppins',
    fontWeight: '700',
    fontSize: 14,
    lineHeight: 21,
  },
  iconPass: {
    width: 25,
    height: 25,
  },
  inputForm: {
    color: 'black',
    borderBottomWidth: 1,
    paddingHorizontal: 5,
    fontFamily: 'poppins',
    fontWeight: '700',
    fontSize: 14,
    borderColor: 'white',
    color: 'white',
    lineHeight: 21,
  },
  btnLogin: {
    backgroundColor: '#FFBA33',
    borderRadius: 20,
    height: 70,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
  },
  textBtnLogin: {
    color: 'black',
    fontWeight: 'bold',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 17,
    lineHeight: 26,
  },
  btnRegis: {
    backgroundColor: '#6A4029',
    borderRadius: 20,
    height: 70,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
  },
  textBtnRegis: {
    color: 'white',
    fontWeight: 'bold',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 17,
    lineHeight: 26,
  },
  btnGoogle: {
    flexDirection: 'row',
    backgroundColor: 'white',
    borderRadius: 20,
    height: 70,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#C7C7C7',
    borderRadius: 20,
  },
  textBtnGoogle: {
    marginLeft: 10,
    color: 'black',
    fontWeight: 'bold',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 17,
    lineHeight: 26,
  },
  sectionLogin: {
    paddingHorizontal: '5%',
    alignItems: 'center',
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  borderFlex: {
    flex: 1,
    borderBottomWidth: 1,
    borderColor: 'white',
  },
});
