import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  containerMain: {
    backgroundColor: '#F2F2F2',
    height: 'auto',
    paddingTop: 50,
    paddingBottom: 50,
  },
  headerText: {
    color: 'black',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '900',
    fontSize: 34,
    lineHeight: 51,
    marginHorizontal: '10%',
    marginBottom: 35,
  },
  boxSection: {
    marginBottom: 35,
    marginHorizontal: '10%',
    paddingVertical: 25,
    backgroundColor: 'white',
    borderRadius: 20,
  },

  headText: {
    color: 'black',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 17,
    lineHeight: 26,
    marginHorizontal: '10%',
    borderBottomWidth: 1,
    marginBottom: 8,
    borderBottomColor: 'rgba(0, 0, 0, 0.3)',
    paddingVertical: 3,
  },
  listBox: {
    marginHorizontal: '10%',
    marginBottom: 8,
    paddingVertical: 3,
    flexDirection: 'row',
    alignItems: 'center',
  },
  boxPay: {
    marginLeft: '10%',
    lineHeight: 26,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.3)',
    flexDirection: 'row',
    flex: 1,
    alignItems: 'center',
    paddingBottom: 15,
  },
  listText: {
    marginLeft: 10,
    color: 'black',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 17,
  },

  Text: {
    marginBottom: 8,
    paddingVertical: 3,
    color: 'black',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 15,
    lineHeight: 22,
    marginHorizontal: '10%',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.3)',
  },
  titleText: {
    color: 'black',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 17,
    lineHeight: 26,
    marginHorizontal: '10%',
    marginBottom: 14,
  },
  totalText: {
    color: 'black',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 17,
    lineHeight: 26,
  },
  priceText: {
    color: 'black',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 22,
    lineHeight: 33,
  },

  btnRegis: {
    marginVertical: 50,
    backgroundColor: '#6A4029',
    borderRadius: 20,
    height: 70,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    marginBottom: 100,
    marginHorizontal: '10%',
  },
  textBtnRegis: {
    color: 'white',
    fontWeight: 'bold',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 17,
    lineHeight: 26,
  },
  boxList: {
    flexDirection: 'row',
    marginHorizontal: '5%',
    marginBottom: 14,
    alignItems: 'center',
  },
  boxImg: {
    flex: 1,
    height: 64,
    borderRadius: 20,
  },
  listInfo: {
    marginLeft: 15,
    flex: 2,
  },
  listPrice: {
    flex: 2,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  textPrice: {
    color: 'black',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 17,
    lineHeight: 26,
  },
  ProductText: {
    color: 'black',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 21,
  },
});
