import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  containerMain: {
    backgroundColor: '#F2F2F2',
    height: 'auto',
    paddingTop: 50,
    paddingBottom: 50,
  },
  boxProduct: {
    backgroundColor: 'red',
  },
  boxCart: {
    height: 127,
    width: '90%',
    margin: '5%',
    flexDirection: 'row',
  },
  boxLeft: {
    backgroundColor: 'white',
    flex: 1,
    height: 102,
    marginTop: 25,
    alignItems: 'center',
    borderRadius: 30,
    shadowColor: 'rgba(57, 57, 57, 0.1',
    shadowOffset: 30,
  },
  imgBox: {
    borderRadius: 100,
    marginTop: -25,
    width: 84.33,
    height: 82.38,
  },
  priceProduct: {
    color: '#895537',
    fontWeight: '700',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 13,
    lineHeight: 26,
  },

  boxRight: {
    flex: 2,
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingLeft: 30,
  },
  nameText: {
    color: 'black',
    fontWeight: '700',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 18,
    lineHeight: 26,
  },
  buletView: {
    marginTop: 10,
    width: '60%',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  bulet: {
    paddingVertical: 1,
    paddingHorizontal: 10,
    borderRadius: 30,
    color: 'black',
    fontWeight: '900',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 18,
    lineHeight: 26,
    backgroundColor: 'rgba(231, 170, 54, 0.52)',
  },
  quantity: {
    color: 'black',
    fontWeight: '900',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 18,
    lineHeight: 26,
  },
  bulletActive: {
    backgroundColor: '#FFBA33',
    borderRadius: 100,
    height: 70,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: '5%',
    marginVertical: '5%',
    flexDirection: 'row',
  },
  bulletActiveEnd: {
    backgroundColor: '#FFBA33',
    borderRadius: 100,
    height: 70,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginHorizontal: '5%',
    marginVertical: '5%',
    flexDirection: 'row',
    marginBottom: 100,
  },
  textBulletActive: {
    alignItems: 'center',
    justifyContent: 'center',
    color: '#6A4029',
    fontWeight: 'bold',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 13,
    lineHeight: 26,
  },
  textBulletActiveEnd: {
    marginLeft: '15%',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#6A4029',
    fontWeight: 'bold',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 13,
    lineHeight: 26,
  },
  struk: {
    borderTopWidth: 1,
    borderTopColor: '#E0E0E2',
    height: 'auto',
    paddingTop: 33,
    marginHorizontal: '5%',
  },
  boxStruk: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: '5%',
    marginVertical: '2%',
  },
  textInfo: {
    color: '#ADADAF',
    fontWeight: 'bold',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 15,
    lineHeight: 26,
  },
  textPrice: {
    color: 'black',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 15,
    lineHeight: 26,
  },
  textTotal: {
    color: 'black',
    fontWeight: 'bold',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 22,
    lineHeight: 36,
  },
  btnRegis: {
    marginVertical: 50,
    backgroundColor: '#6A4029',
    borderRadius: 20,
    height: 70,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    marginBottom: 100,
    marginHorizontal: '10%',
    flexDirection: 'row',
  },
  textBtnRegis: {
    color: 'white',
    fontWeight: 'bold',
    fontFamily: 'Poppins',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 17,
    lineHeight: 26,
  },
});
