import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  containerMain: {
    backgroundColor: '#F2F2F2',
    height: '100%',
  },
  headerText: {
    fontFamily: 'Poppins',
    fontSize: 34,
    fontStyle: 'normal',
    fontWeight: '900',
    lineHeight: 51,
    color: 'black',
    marginLeft: '10%',
    marginRight: '15%',
  },
  searchInput: {
    backgroundColor: '#EFEEEE',
    height: 60,
    width: '80%',
    marginHorizontal: '10%',
    borderRadius: 30,
    marginVertical: 10,
  },
  inputBox: {
    fontFamily: 'Poppins',
    fontSize: 17,
    fontStyle: 'normal',
    fontWeight: '900',
    lineHeight: 26,
    color: 'black',
  },
  menuBar: {
    marginLeft: '10%',
    marginTop: 36,
    minHeight: 30,
  },
  listMenu: {
    padding: 5,
    paddingHorizontal: 10,
    marginHorizontal: 5,
  },
  listMenuActive: {
    padding: 5,
    paddingHorizontal: 10,
    borderBottomColor: '#6A4029',
    borderBottomWidth: 2,
    marginHorizontal: 5,
  },
  menuText: {
    fontFamily: 'Poppins',
    fontSize: 17,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 26,
    color: '#9A9A9D',
  },
  menuTextActive: {
    fontFamily: 'Poppins',
    fontSize: 17,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 26,
    color: '#6A4029',
  },
  textLink: {
    marginTop: 45,
    textAlign: 'right',
    marginRight: '10%',
    fontFamily: 'Poppins',
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 22,
    color: '#6A4029',
  },
  listItem: {
    marginTop: 20,
    marginLeft: '10%',
    height: 250,
  },
  item: {
    backgroundColor: 'white',
    width: 200,
    height: 220,
    marginTop: 30,
    alignItems: 'center',
    borderRadius: 30,
    shadowColor: 'rgba(57, 57, 57, 0.1)',
    shadowOffset: 2,
    marginRight: 30,
  },
  itemImg: {
    width: 150,
    height: 150,
    marginTop: -30,
    marginBottom: 16,
    borderRadius: 20,
  },
  itemText: {
    fontFamily: 'Poppins',
    fontSize: 22,
    fontStyle: 'normal',
    fontWeight: '900',
    lineHeight: 22.2,
    color: 'rgba(0, 0, 0, 0.9)',
    textAlign: 'center',
    marginHorizontal: '25%',
  },
  itemPrice: {
    fontFamily: 'Poppins',
    fontSize: 17,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 26,
    color: '#6A4029',
    textAlign: 'center',
  },
});
